### ISSUE TITLE
no perf data - java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by l7s** [crate/crate#2463]
Not sure if related to #2461 but after upgrading to 0.50.3 from 0.48.6 web admin console shows "No data" in performance graph, and Cluster tab doesn't show any nodes. When I look into firebug /_sql 

    {"stmt":"select id, name, hostname, rest_url, port, load, heap, fs, os['cpu'] as cpu, load, version, os['probe_timestamp'] as timestamp, process['cpu'] as proc_cpu from sys.nodes"}

returns 500 error with the following response:

    {"error":{"message":"SQLActionException[java.lang.NoClassDefFoundError: ]","code":5000}}

What perhaps might be relevant is we run our cluster on Virtuozzo VMs.

**Comment by mfussenegger** [comment]
This is probably related.
Could it be that you've files from the old crate version in your classpath? How did you upgrade crate?

**Comment by l7s** [comment]
We install / upgrade crate manually by downloading .tar.gz package to /opt folder, decompressing it and next I have a simple bash script to run it:

    ver="0.50.3"

    export CRATE_HEAP_SIZE=8192m
    export JAVA_HOME=/opt/jre1.8.0_60
    nohup /opt/crate/bin-$ver/crate >> /var/log/crate/crate-bin.log 2>&1 &

**Comment by mfussenegger** [comment]
Can you try to clear the `/opt/crate/lib/` folder and then re-add all jar files from the downloaded package? You have probably lucene jars from the old crate version AND from the new crate version and that is causing your issues.

**Comment by l7s** [comment]
removed `/opt/crate` and decopressed all files from `crate-0.50.3.tar.gz` and now I am getting different error:

    {"error":{"message":"SQLActionException[java.lang.IllegalAccessError: tried to access method .access$000()Lcom/carrotsearch/hppc/IntSet; from class io.crate.operation.reference.sys.node.fs.FileSystems$1]","code":5000}}

**Comment by mfussenegger** [comment]
Is hppc-<someversion>.jar present in the `/opt/crate/lib` folder? 
Do you have the CRATE_CLASSPATH env variable set and if so, does it contain any other folders besides the crate 0.50.3 specific ones?

Unfortunately the full classpath that you've got was trimmed in the error output that you posted in the other issue.

**Comment by l7s** [comment]
I have actually moved crate from `/opt/crate` to `/opt/crate-0.50.3` but yes, there is `hppc-0.6.0.jar` file in `/opt/crate-0.50.3/lib` folder

    $ find /opt/crate-0.50.3 -type f -name 'hppc*'
    /opt/crate-0.50.3/lib/hppc-0.6.0.jar

I don't set `CRATE_CLASSPATH` the only two env variables I set before starting crate are:

    export CRATE_HEAP_SIZE=8192m
    export JAVA_HOME=/opt/jre1.8.0_60

**Comment by mfussenegger** [comment]
Closing this as it is related to https://github.com/crate/crate/issues/2461
