### PR TITLE
 Don't skip validation of first record when inserting an array

### LINKED ISSUE #19231: HTTP protocol decoding anomaly with inner types on ARRAY columns
## About
After a recent improvement landed in CrateDB nightly that changed behaviour on data structure serialization/decoding details when using the HTTP protocol, we observe more strictness of CrateDB when it comes to matching INSERT data to the designated table schema. We think it is a good thing [^1], but we have been able to observe an anomaly. We selected CrateDB 6.2.0 for reference purposes, and compared with CrateDB nightly.

[^1]: FYI: It made us discover a flaw in a downstream adapter package, see [Wrong SQL DDL for `melty.countries` table](https://github.com/crate/meltano-target-cratedb/issues/93).

## Details
The error manifests when a table schema includes a column definition that uses the `ARRAY(STRING)` type, and you will submit a different inner type when using a parameterized INSERT statement over HTTP. In this case, the error materializes when submitting an `OBJECT` inner type, effectively `ARRAY(OBJECT(DYNAMIC))` instead of `ARRAY(STRING)`.

## Previous behavior
When submitting a single record using a parameterized INSERT statement over HTTP, the incantation succeeds on both CrateDB 6.2.0 and CrateDB nightly.
```
uvx crash -c 'drop table if exists t01;'
uvx crash -c 'create table t01 (id text, data array(string));'
uvx --from httpie http localhost:4200/_sql \
  stmt='insert into t01 (id, data) values (?, ?)' \
  args:='["a", [{"foo":"bar"}]]' --print bB
uvx crash -c 'refresh table t01;'
uvx crash -c 'select * from t01;'
```
```
+----+-----------------------+
| id | data                  |
+----+-----------------------+
| a  | ["{\"foo\":\"bar\"}"] |
+----+-----------------------+
SELECT 1 row in set (0.028 sec)
```

## New behavior
When submitting more than a single record using a parameterized INSERT statement over HTTP, the incantation succeeds on CrateDB 6.2.0, but fails on CrateDB nightly.
```
uvx crash -c 'drop table if exists t01;'
uvx crash -c 'create table t01 (id text, data array(string));'
uvx --from httpie http localhost:4200/_sql \
  stmt='insert into t01 (id, data) values (?, ?), (?, ?)' \
  args:='["a", [{"foo": "bar"}], "b", [{"foo": "bar"}]]' --print bB
uvx crash -c 'refresh table t01;'
uvx crash -c 'select * from t01;'
```
```python
SQLParseException[
The types of the columns within VALUES lists must match.
Found `text_array` and `object_array` at position: 1]
```

## Evaluation / Thoughts
Earlier versions of CrateDB accepted the type mismatch and simply stored the OBJECT inner value verbatim into STRING, which is technically wrong. CrateDB nightly is doing better by rejecting the INSERT operation, and we think it's a positive improvement. However, to conclude the new strictness, it might also want to be applied in single-record-insert edge case situations like demonstrated above, when possible.

Also, we might think about improving the CrateDB change log by mentioning this strictness improvement on SQL DDL vs. DML in one way or another, but more prominently, because it might break innocent people's systems in the same way like our little CI/GHA recipe started failing. By letting them find a corresponding description in the change log file, it will save people significant amounts of trial-and-error cycles.

## References
- https://github.com/crate/crate/pull/19212
- https://github.com/crate/cratedb-examples/issues/1541

### PR DESCRIPTION
**Pull request by hariso**
## Summary of the changes / Why this improves CrateDB

Closes https://github.com/crate/crate/issues/19231.

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java [hunk 1]
```diff
@@ -838,9 +838,8 @@ public AnalyzedRelation visitValues(Values values, StatementAnalysisContext cont
                 columnValues.add(cell);
 
                 var cellType = cell.valueType();
-                if (r > 0 // skip first cell, we don't have to check for self-conversion
```
Comment (hariso) [inline server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java:841]: Introduced in https://github.com/crate/crate/pull/9528/changes#diff-4c91b512011cc00c6f28165439030424e126a4f446198ccb9c4cb84a49a6a7beR765, when target types were deduced from input values.

File: server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java [hunk 2]
```diff
@@ -99,6 +99,19 @@ public void test_process_values_result_in_table_function_with_values_name() {
...
+        var executor = SQLExecutor.of(clusterService)
+            .addTable("create table t01 (id text, data array(string));");
+
+        executor.execute("insert into t01 (id, data) values (?, ?), (?, ?)", new Object[][] {
+            new Object[] { "a", new Object[] {Map.of("foo", "bar")}},
+            new Object[] { "a", new Object[] {Map.of("foo", "bar")}}
+        });
+
+        System.out.println();
+    }
```
Comment (mfussenegger) [inline server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java:125]: Test says "incompatible types" but doesn't fail? Is the insert working, or is there count 0?
Also remove the println?

**Review by mfussenegger — COMMENTED** [review]
Shouldn't this have a changes entry since it is changing user observable behavior?

File: server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java (hunk 2 above)
Comment (hariso) [reply server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java:125]: Argh, didn't finish this test. The PR needs to be wrapped up after all.:) Sorry about this, I'll ping once I'm done with this.

Comment (hariso) [reply server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java:125]: @mfussenegger Now it's done. I remembered I wanted to move the test from `RestSQLActionIntegrationTest` to here.

**Comment by hariso** [comment]
> Shouldn't this have a changes entry since it is changing user observable behavior?

You're right, added something now.

File: docs/appendices/release-notes/6.4.0.rst [hunk 3]
```diff
@@ -178,3 +155,10 @@ Client interfaces
 
       The types of the columns within VALUES lists must match.
       Found `text_array` and `object_array` at position: 1
+
+Fixes
+=====
+
+- Fixed an issue where data type validation was skipped on the first element of
```
Comment (mfussenegger) [inline docs/appendices/release-notes/6.4.0.rst]: x.y.0 feature releases must never have any fixes. Either we frame this as a behavior change - e.g. in the breaking section or this must go into 6.3.x as a hotfix.

Also: If the validation was skipped - what was the behavior? Did the value get inserted in an incorrect format or was it rejected later anyway? It's not clear from the entry.

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst]: Fair point, I'll clarify (the behavior I observed is the same as in the original issue).

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst]: Done, I force-pushed the branch with the updated RN.

File: docs/appendices/release-notes/6.4.0.rst [hunk 4]
```diff
@@ -44,7 +44,13 @@ Version 6.4.0 - Unreleased
...
 ================
 
-None
+- Changed how type validation is enforced on array parameters in inserts or
+  updates. Previously, type validation was skipped on the first element of an
+  array value but enforced on the rest. The first element was implicitly cast if
+  possible and inserted/updated. With this version, the validation of data type
+  is enforced on each element equally. With this, some queries that previously
+  succeeded now fail, especially array parameters with one element.
+
```
Comment (matriv) [inline docs/appendices/release-notes/6.4.0.rst:64]: I think an example here would be helpful, especially because it's a breaking change, to make it clear for the users, thx!

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst:64]: I was thinking about that, but it would make the entry a bit long, and it seems to me they usually aren't. But give me a bit, I'll try to come up with smth concise.

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst:64]: I was thinking about that, but it would make the entry a bit long, and it seems to me they usually aren't. But give me a bit, I'll try to come up with smth concise.

Comment (mfussenegger) [reply docs/appendices/release-notes/6.4.0.rst:64]: How about something like:

```
- Changed the type validation for ``INSERT INTO`` to be stricter if using
  parameter placeholders and providing a single `VALUES`` row.
  Before casts like object-array to string-array were allowed
  if there was a single value, but not if there were many values.

  For example, in:

      INSERT INTO tbl (xs) VALUES ($1)
      INSERT INTO tbl (xs) VALUES ($1), ($1)

  With ``xs`` as ``text[]`` column and ``$1`` as ``[{"x": 10}]`` object array,
  the first statement inserted the object array as JSON string and the second
  statement was rejected. With the change, both statements are rejected.
```

Comment (matriv) [reply docs/appendices/release-notes/6.4.0.rst:64]: I think it reads well like that, thx!

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst:64]: Thanks Mathias! I've added your example (might some tiny polishing).

**Review by mfussenegger — APPROVED** [review]
